---
# file: roles/dynamicnamespace/tasks/secrets/docker_pull.yml
# Group of task for create secret with credentials for docker registry
# In this tasks variable from cr save to file and then file will included as variable.
# Looks strange but we cant use ansible-vault variables in cr definition.

- name: Var extraction
  block:
    - name: Create tempfile
      tempfile:
        state: file
        prefix: dynns.
      register: __dynns_pull_temp
      changed_when: false

    - name: Copy token from cr to file
      copy:
        content: "{{ registry_creds.password|b64decode }}"
        dest: "{{ __dynns_pull_temp.path }}"
        mode: "0644"
      changed_when: false
  delegate_to: localhost

- name: Include var with registryCreds from file
  include_vars:
    file: "{{ __dynns_pull_temp.path }}"

- name: Remove tempfile
  file:
    path: "{{ __dynns_pull_temp.path }}"
    state: absent
  changed_when: false
  delegate_to: localhost

- name: Set intermediate variable
  set_fact:
    _dynns_docker_reg_cred:
      username: "{{ registry_creds.user }}"
      password: "{{ _dynns_registry_pass|string }}"
      auth: "{{ (registry_creds.user ~ ':' ~ _dynns_registry_pass|string)|b64encode }}"

- name: Set full secret variable
  set_fact:
    _docker_pull_secret:
      auths:
        '{ "{{ registry_creds.url }}": {{ _dynns_docker_reg_cred }} }'

- name: Create registry secret
  k8s:
    api_version: v1
    kind: Secret
    name: registry-cred
    namespace: "{{ meta.name }}"
    resource_definition:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ _docker_pull_secret|to_json|b64encode }}"
...
