---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: metadynamicnamespaces.devops.slurm.io
spec:
  group: devops.slurm.io
  names:
    kind: MetaDynamicNamespace
    listKind: MetaDynamicNamespaceList
    plural: metadynamicnamespaces
    shortNames:
    - metadynns
    singular: metadynamicnamespace
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              dynnsCrQuota:
                type: integer
                minimum: 0
                maximum: 200
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: QUOTA
      type: string
      description: Dynamic namespaces quota for this project
      jsonPath: .spec.dynnsCrQuota
    - name: AGE
      type: date
      jsonPath: .metadata.creationTimestamp
...
