---
# file: roles/dynamicnamespace/task/rbac/psp.yml
# Group of task for create a role and rolebinding for use psp

- name: Create a role for PSP
  k8s:
    api_version: rbac.authorization.k8s.io/v1
    kind: Role
    name: "operator:dynns:psp"
    namespace: "{{ meta.name }}"
    resource_definition:
      rules:
      - apiGroups:
        - policy
        resources:
        - podsecuritypolicies
        verbs:
        - use
        resourceNames:
        - "{{ psp_name }}"

- name: Create rolebinding for PSP
  k8s:
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: "operator:dynns:psp"
    namespace: "{{ meta.name }}"
    resource_definition:
      roleRef:
        kind: Role
        name: "operator:dynns:psp"
        apiGroup: rbac.authorization.k8s.io
      subjects:
      - kind: Group
        apiGroup: rbac.authorization.k8s.io
        name: system:authenticated
...
